title: Human Programmer
name: Andrew Quan
description: A programming blog written by a human, for other humans
email: andrewhquan@gmail.com
timezone: Asia/Tokyo

personal_page_url: andrewquan.github.io
linkedin_username: andrewhquan
github_username: andrewquan
